### PR TITLE
Add note about Anapaya patches to `control` file

### PR DESCRIPTION
**Pull request by klausman**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/quagga/4)

### CODE REVIEW

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[debian/control, line 113 at r1](https://reviewable.io/reviews/anapaya/quagga/4#-LDkCJ3FCHG-nOfAC4RZ:-LDkCJ3FCHG-nOfAC4R_:b9nh8wp) ([raw file](https://github.com/anapaya/quagga/blob/80156954f56b9051dda20ee3c25e1c5a35f23308/debian/control#L113)):*
> ```
>  This package is built from a version of Quagga patched by the SCION project.
>  The relevant source can be found at: https://github.com/Anapaya/quagga
> ```

Extra blank line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/4)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[debian/control, line 61 at r1](https://reviewable.io/reviews/anapaya/quagga/4#-LDkDwWK5UiILKgjhTqY:-LDkDwWK5UiILKgjhTqZ:b-9nr3js) ([raw file](https://github.com/anapaya/quagga/blob/80156954f56b9051dda20ee3c25e1c5a35f23308/debian/control#L61)):*
> ```
> SCION project
> ```
s/the SCION project/Anapaya Systems/g

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/4)*

**Comment by klausman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[debian/control, line 61 at r1](https://reviewable.io/reviews/anapaya/quagga/4#-LDkDwWK5UiILKgjhTqY:-LDkF0WvAKqHdKsu0ztg:b-896fix) ([raw file](https://github.com/anapaya/quagga/blob/80156954f56b9051dda20ee3c25e1c5a35f23308/debian/control#L61)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

> ```
> SCION project
> ```
s/the SCION project/Anapaya Systems/g
</blockquote></details>

Done.

---

*[debian/control, line 113 at r1](https://reviewable.io/reviews/anapaya/quagga/4#-LDkCJ3FCHG-nOfAC4RZ:-LDkF0o19GeqoateLLh4:b-896fix) ([raw file](https://github.com/anapaya/quagga/blob/80156954f56b9051dda20ee3c25e1c5a35f23308/debian/control#L113)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Extra blank line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/4)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/4)*

**Comment by kormat** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/4#-:-LDkGVL46xiL_A184iSO:bnfp4nl)*

**Pull request merged**
