### PR TITLE
Patched zebra to include a new route type for the SIG

### PR DESCRIPTION
**Pull request by shitz**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/quagga/2)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 15 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBaAlfuBEEKo1pIqwjt:-LBaAlfuBEEKo1pIqwju:bptedmn) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L15)):*
> ```Diff
>  ZEBRA_ROUTE_BABEL,  "Babel routing protocol (Babel)"
>  ZEBRA_ROUTE_NHRP,   "Next Hop Resolution Protocol (NHRP)"
> +ZEBRA_ROUTE_SIG,    "SCION-IP Gateway exported route"
> ```

`SCION IP-Gateway`

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 22 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBaCc0B1wk8QOtOef6m:-LBaCc0B1wk8QOtOef6n:b8arycu) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L22)):*
> ```Diff
>    [ZEBRA_ROUTE_BABEL]   = {ZEBRA_ROUTE_BABEL,    95},
>    [ZEBRA_ROUTE_NHRP]    = {ZEBRA_ROUTE_NHRP,     10},
> +  [ZEBRA_ROUTE_SIG]     = {ZEBRA_ROUTE_SIG,       2},
> ```

Why `2`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/2)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 22 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBaCc0B1wk8QOtOef6m:-LBaHIrA0_xYfMWLzybc:b8bt5uc) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L22)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why `2`?
</blockquote></details>

`kernel` has 0 and `static` has 1. I thought the SIG routes should have a distance that is larger than kernel and static routes, but lower than anything else.

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/2)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 1 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBabA_O9wfxSLLrERP3:-LBabA_P5mxWUZqK1Jq8:b-2kesxy) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L1)):*
> ```Diff
> --- a/lib/route_types.txt
> ```

`zebra/zebra_rib.c:meta_queue_map` isn't changed - does it need to be?

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 22 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBaCc0B1wk8QOtOef6m:-LBaVabyDraPmQd7zx_Q:b-s2c8h4) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L22)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`kernel` has 0 and `static` has 1. I thought the SIG routes should have a distance that is larger than kernel and static routes, but lower than anything else.
</blockquote></details>

Ok, fair enough :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/2)*

**Comment by shitz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 1 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBabA_O9wfxSLLrERP3:-LBdpt5LDwbsMkv115sI:b6zrrk4) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`zebra/zebra_rib.c:meta_queue_map` isn't changed - does it need to be?
</blockquote></details>

Good catch!

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 15 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBaAlfuBEEKo1pIqwjt:-LBdrJhr5ybhWNbJjCo_:b3cod7v) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L15)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`SCION IP-Gateway`
</blockquote></details>

According to the book (and also all my presentations, handouts etc) it's spelled `SCION-IP Gateway`. When I pronounce it, I make a short pause after `SCION-IP` and not after `SCION`, so it seems to me that this is the correct spelling.

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/2)*

**Comment by shitz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 15 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBaAlfuBEEKo1pIqwjt:-LBehsPk1aZ7AwqjGrp4:bhxqfa0) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L15)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

According to the book (and also all my presentations, handouts etc) it's spelled `SCION-IP Gateway`. When I pronounce it, I make a short pause after `SCION-IP` and not after `SCION`, so it seems to me that this is the correct spelling.
</blockquote></details>

Done. Happy?

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/2)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[debian/patches/0011-Add-SIG-Route-Type.patch, line 15 at r1](https://reviewable.io/reviews/anapaya/quagga/2#-LBaAlfuBEEKo1pIqwjt:-LBefqrS-lkLdwPSU-dK:b-1ft4mm) ([raw file](https://github.com/anapaya/quagga/blob/005905b61583c99e9ce37feea5ca7fcab27381ef/debian/patches/0011-Add-SIG-Route-Type.patch#L15)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Done. Happy?
</blockquote></details>

Ok, i can confirm that when tobias and i originally wrote the chapter for the book we _did_ call it the `SCION-IP Gateway`, but i still contend that this is wrong. It is an IP gateway for SCION. It is not a gateway for SCION-IP (whatever that would be).

Delighted :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/anapaya/quagga/2#-:-LBej6yQ9CKxQI0XiBhv:bnfp4nl)*

**Pull request merged**
